### ISSUE TITLE
F-Droid screenshots

### ISSUE THREAD

**Issue by michaelblyons** [thelooter/labplus_for_gitlab#45]
Congrats on getting into the F-Droid store!

I noticed that there were no app screenshots for Lab+ on the store, but you have some in the ReadMe. I think there's probably just some metadata wiring to get those into the store entry, too.

Good luck!

**Comment by thelooter** [comment]
Thanks for the feedback. Yes there are some screenshots in the README, but those were from before this project was forked from https://github.com/mgvora/gitplus_for_gitlab

I will try to get up to date Screenshots into the next release
