### ISSUE TITLE
Impossible to login with basic auth when using 2FA on account

### ISSUE THREAD

**Issue by Int-Circuit** [thelooter/labplus_for_gitlab#51]
When using the basic auth option (regardless of http/https) with an account with 2FA, you get an "unauthorized" error. This makes the basic auth option useless as the only other option is to use a PAT token to login

**Comment by thelooter** [comment]
This is a limitation of the Gitlab API. This is not something I can currently fix. See here for more details
https://docs.gitlab.com/ee/user/profile/account/two_factor_authentication.html#use-personal-access-tokens-with-two-factor-authentication

**Comment by thelooter** [comment]
Are there still anymore questions or can I close this issue

**Comment by Int-Circuit** [comment]
Thx for the explanation, hope you have a great day
