### ISSUE TITLE
Different Fork of this project are on Play Store and App Store.

### ISSUE THREAD

**Issue by jayb-g** [thelooter/labplus_for_gitlab#60]
I came accross [Git+](https://github.com/mgvora/gitplus_for_gitlab), I see @mgvora as a contributor to both projects. Although Git+ is on Play store and App store, Lab+ is not. 

What are the differences between the two apps? Which one is the original?

**Comment by thelooter** [comment]
Git+ is the original, but the repository seemed abandoned, so I forked it. I haven't yet been able to publish to the Playstore and have no access to a Mac to compile for the App Store.

This project has fixed some issues of the original App and is still maintained
